Feature/22
emodyz/MultigamingPanel pull request #49
Opened 2021-01-15 19:02 UTC by leohubert

This PR close #22

2021-01-16 22:11 UTC, leohubert commented
Wait avant de merger, 2/3 truc à faire 

Tu peux dès à présent faire une première passe sur le code :)

2021-01-16 22:29 UTC, leohubert commented on app/Actions/Emodyz/ModPacks/EditModPack.php
> +      throw ModPackException::invalidDisk($disk);
Pas sûr pour le `throw` @iWirk  tu en penses quoi ?

2021-01-16 22:29 UTC, leohubert commented on resources/js/Pages/ModPacks/Components/CreateModPackModal.vue
> +            <DocumentAdd class="ml-2 h-4 w-4"/>
Changer l'icone `DocumentAdd` par un `FolderAdd`

2021-01-16 22:29 UTC, leohubert commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +            disk (optional) of this modpack.
Retirer `disk` car non modifiable pour le moment

2021-01-16 22:29 UTC, leohubert commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +                        placeholder="My Amazing Name..."
Modpack path...

2021-01-16 22:29 UTC, leohubert commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +    _method: 'PUT',
Retirer  ` _method: 'PUT',`
Changer `this.$inertia.form` par `this.$inertia.put`

2021-01-16 22:29 UTC, leohubert commented on resources/js/Pages/ModPacks/Index.vue
> +    /* {
On retire ça ?

2021-01-16 22:29 UTC, leohubert commented on resources/js/Pages/ModPacks/Update.vue
> +                            <svg id="ac59e0a9-a4b2-4068-bf01-0bc90fb884ae" data-name="Layer 1"
Mettre le SVG dans un component approprié !

2021-01-16 22:29 UTC, leohubert commented on resources/js/Shared/DataTable/Components/Actions.vue
> +              <span class="text-md">Are you sure you would like to delete this modpack ?</span>
Un petit <br> et un petit style sur le ` {{ item.metaData.name }}`

2021-01-16 22:29 UTC, leohubert commented on resources/js/Shared/DataTable/Components/GameProfile.vue
> +      <div class="text-sm font-medium text-gray-900">
En gras ?

2021-01-16 22:29 UTC, leohubert commented on resources/js/Shared/DataTable/Components/ModPackServers.vue
> +<template>
Plus utilisé ce composant me semble, retirer tout ça si c'est le cas

2021-01-16 22:29 UTC, leohubert commented on resources/js/Shared/DataTable/DataTable.vue
> +import DtModPackServers from '@/Shared/DataTable/Components/ModPackServers.vue'
Clean `DtModPackServers`

2021-01-16 22:29 UTC, leohubert commented on resources/js/app.ts
> +      resolveErrors: (page: any) => (page.props.errors || {}),
On peut retirer ça depuis Inertia 0.8

2021-01-16 22:29 UTC, leohubert commented on tests/Feature/ModPacks/ModPackControllerTest.php
> +            'batch',
Ajouter la validation du `game`

2021-01-17 09:57 UTC, iWirk commented on app/Actions/Emodyz/ModPacks/EditModPack.php
> +      throw ModPackException::invalidDisk($disk);
je pense que c'est une bonne idee d'avoir une exception pour ce genre de erreur fatale (plus simple a debug

2021-01-17 09:57 UTC, iWirk commented on resources/js/Pages/ModPacks/Components/CreateModPackModal.vue
> +            <DocumentAdd class="ml-2 h-4 w-4"/>
yes please!

2021-01-17 15:59 UTC, iWirk requested changes

2021-01-17 15:59 UTC, iWirk commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +                        placeholder="My Amazing Name..."
hum, tu veux en fair quoi ?

2021-01-17 15:59 UTC, iWirk commented on resources/js/Pages/ModPacks/Index.vue
> +    /* {
yep

2021-01-17 15:59 UTC, iWirk commented on resources/js/Shared/DataTable/Components/Actions.vue
> +              <span class="text-md">Are you sure you would like to delete this modpack ?</span>
yes un `<br/>` un un `text-xs/sm`

2021-01-17 15:59 UTC, iWirk commented on resources/js/Shared/DataTable/Components/GameProfile.vue
> +      <div class="text-sm font-medium text-gray-900">
`font-semibold`

2021-01-17 15:59 UTC, iWirk commented on resources/js/Shared/DataTable/Components/ModPackServers.vue
> +<template>
yes useless

2021-01-17 15:59 UTC, iWirk commented on resources/js/Shared/Svgs/Spinner.vue
> +<style scoped>
useless nan ?

2021-01-17 15:59 UTC, iWirk commented on resources/js/app.ts
> +      resolveErrors: (page: any) => (page.props.errors || {}),
je pense les laisser au cas ou on doir fair une requete avec axios ca permet de catch les erreurs du validator

2021-01-17 15:59 UTC, iWirk commented on tests/Feature/ModPacks/ModPackControllerTest.php
> +            'batch',
yass plz

2021-01-17 15:59 UTC, iWirk commented on resources/js/Shared/DataTable/DataTable.vue
> +import DtModPackServers from '@/Shared/DataTable/Components/ModPackServers.vue'
yes

2021-01-17 15:59 UTC, iWirk commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +            disk (optional) of this modpack.
tu peux le laisser afficher en mode comming soon mais ca sert a rien de l'envoyer dans ton form

2021-01-17 15:59 UTC, iWirk commented on resources/js/Pages/ModPacks/Update.vue
> +                            <svg id="ac59e0a9-a4b2-4068-bf01-0bc90fb884ae" data-name="Layer 1"
yes stp

2021-01-18 08:40 UTC, leohubert commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +                        placeholder="My Amazing Name..."
Pour pouvoir changer le path de ton modpack sur le serveur

2021-01-18 09:40 UTC, iWirk commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +                        placeholder="My Amazing Name..."
Ah ok yes , faudrait le rendre fonctionnel avant un merge

2021-01-18 10:12 UTC, leohubert commented on resources/js/Pages/ModPacks/Components/EditModPackForm.vue
> +                        placeholder="My Amazing Name..."
Déjà le cas ;)

2021-01-18 13:31 UTC, iWirk approved these changes
All Good for now

2021-01-18 13:32 UTC, merged