Feature #77 | Docker Support
emodyz/MultigamingPanel pull request #78
Opened 2021-03-03 16:58 UTC by iWirk

this pr resolves #77

2021-04-19 16:08 UTC, leohubert requested changes

2021-04-19 16:08 UTC, leohubert commented on routes/web.php
> +Route::get('test', function () {
Cleanup ?

2021-04-19 16:08 UTC, leohubert commented on docker-compose.yml.bak
> +# For more information: https://laravel.com/docs/sail
C'est pour quoi ce fichier ?

2021-04-19 16:08 UTC, leohubert commented on docker/app/app.conf
> +    #ssl_certificate /etc/letsencrypt/live/emodyz.com/fullchain.pem;
Cleanup ça ?

2021-04-19 16:08 UTC, leohubert commented on docker/app/index.php
> +<?php
Remove :)

2021-04-19 16:08 UTC, leohubert commented on docker/app/test.conf
> +    #ssl_certificate /etc/letsencrypt/live/emodyz.com/fullchain.pem;
Cllleann

2021-04-19 16:08 UTC, leohubert commented on docker/php/php.ini
> +;TODO: add OPCache config
TODO ?

2021-04-19 16:08 UTC, leohubert commented on docker/php/Dockerfile
> +# TODO: Add supervisord for laravel queue:work
TODO ?

2021-04-19 16:08 UTC, leohubert commented on docker/php/supervisord.conf
> +[unix_http_server]
Tu as carrément fait un supevisord pour PHP ?

2021-05-05 18:15 UTC, iWirk commented on docker-compose.yml.bak
> +# For more information: https://laravel.com/docs/sail
le fichier yml de sail a l'avenire avoir les 2 cote a cotes pour pouvoir utiliser sail  en dev et ezg cli en prod depuis le meme repo

2021-05-05 18:17 UTC, iWirk commented on docker/php/php.ini
> +;TODO: add OPCache config
l'OPCACHE est activer par default mais pour le moment on a pas de charge suffisante a examiner pour pouvoir tune la config

2021-05-05 18:20 UTC, iWirk commented on docker/php/supervisord.conf
> +[unix_http_server]
copier le tien et ca marche perfect pour gérer les workers de queue et le server de sockets

2021-08-20 14:50 UTC, leohubert commented on tailwind.config.js
> +  mode: 'jit',
Ah ça y est c'est fix ça ?

2021-08-23 08:40 UTC, leohubert approved these changes

2021-08-23 08:40 UTC, leohubert commented on resources/js/Pages/Articles/Components/EditArticleForm.vue
> +        <!-- TODO: Add a status indicator. ie. BADGES: Draft Or Published
Yes good point !

2022-04-27 18:37 UTC, FlashModz commented on tailwind.config.js
> +  mode: 'jit',
👋

2022-07-04 13:40 UTC, merged